/**
 * Generates src/slugs.ts from the site's post filenames so the API only
 * accepts likes for articles that actually exist. Runs as the functions
 * prebuild hook; the output is gitignored (derived, never hand-edited).
 */
import { readdirSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const postsDir = path.join(here, "..", "..", "src", "content", "posts");
const outFile = path.join(here, "..", "src", "slugs.ts");

const slugs = readdirSync(postsDir)
  .filter((f) => f.endsWith(".md"))
  .map((f) => f.replace(/\.md$/, ""))
  .sort();

if (slugs.length === 0) {
  throw new Error(`gen-slugs: no posts found in ${postsDir}`);
}

const body =
  "// Generated by scripts/gen-slugs.mjs — do not edit.\n" +
  `export const SLUGS: readonly string[] = ${JSON.stringify(slugs, null, 2)};\n`;

writeFileSync(outFile, body);
console.log(`gen-slugs: ${slugs.length} slugs → src/slugs.ts`);
